server:
    port: 9000
logging:
    level:
        org.springframework.security: trace

spring:
    application:
        name: authserver
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/oauth2_db
        username: root
        password: password
    flyway:
        enabled: true
        baseline-on-migrate: true
        validate-on-migrate: true
        locations: classpath:db/migration
        fail-on-missing-locations: true

